# Generated by Django 5.0 on 2024-02-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topic_event_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='points',
            new_name='team_points',
        ),
    ]
