# Generated by Django 5.0 on 2024-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_points_team_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
