# Generated by Django 5.0 on 2024-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_team_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.TextField(null=True),
        ),
    ]
